#!/usr/bin/env python3
"""Regenerate FMS/legacy_funcs.py from the legacy strategy sources.

The functions listed here are copied byte-for-byte out of FMS/legacy/xs0_delta.py
and FMS/legacy/xs1_c_full.py (FuzzingBrain snapshot 4d7eee6c). They are the
prompt builders and output helpers; keeping them verbatim is what makes F(MS) a
reproduction rather than a rewrite. The header supplies the few names they use
from the rest of the legacy script (log_message, call_llm, MAX_INPUT_TOKENS).

    python3 FMS/tools/extract_legacy.py
"""
import ast
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
LEGACY = HERE / "legacy"
OUT = HERE / "legacy_funcs.py"

WANT = {
    "xs0_delta.py": [
        "truncate_output",
        "filter_instrumented_lines",
        "extract_crash_output",
        "process_large_diff",
        "create_commit_based_prompt",
    ],
    "xs1_c_full.py": [
        "_count_tokens",
        "find_most_likely_vulnerable_functions",
        "extract_vulnerable_functions",
        "get_vulnerable_function_entry",
        "_iter_chunks",
        "covert_target_functions_format",
        "create_call_path_info_prompt",
        "create_full_scan_prompt",
    ],
}
# Module-level string constants copied as-is: (file, name, exported as).
CONSTS = [
    ("xs0_delta.py", "SYSTEM_PROMPT", "SYSTEM_PROMPT_DELTA"),
    ("xs1_c_full.py", "SYSTEM_PROMPT", "SYSTEM_PROMPT_FULL"),
    ("xs1_c_full.py", "MAX_INPUT_TOKENS", "MAX_INPUT_TOKENS"),
]

HEADER = '''# SPDX-License-Identifier: Apache-2.0
"""GENERATED by FMS/tools/extract_legacy.py -- do not edit by hand.

Functions copied verbatim from FuzzingBrain's legacy strategies
(crs/strategy/jeff/xs0_delta.py and xs1_c_full.py, snapshot 4d7eee6c).
The names they need from the rest of the legacy script are provided below:
log_message writes to the FMS run log, call_llm goes to the FMS LLM client.
"""
import json
import os
import re
import textwrap
import time

_LLM = None      # set by FMS.substrate.bind_legacy()
_LOG = None


def log_message(log_file, message):
    if _LOG is not None:
        _LOG(message)


def call_llm(log_file, messages, model_name):
    return _LLM(messages, model_name)

'''


def main():
    parts = [HEADER]
    for fname, name, alias in CONSTS:
        src = (LEGACY / fname).read_text()
        for node in ast.parse(src).body:
            if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == name for t in node.targets
            ):
                value = ast.get_source_segment(src, node.value)
                parts.append(f"# {fname}:{node.lineno}\n{alias} = {value}\n\n")
                break
        else:
            raise SystemExit(f"{fname}: constant {name} not found")
    for fname, names in WANT.items():
        src = (LEGACY / fname).read_text()
        defs = {n.name: n for n in ast.parse(src).body if isinstance(n, ast.FunctionDef)}
        for name in names:
            node = defs[name]
            start = node.decorator_list[0].lineno if node.decorator_list else node.lineno
            text = "\n".join(src.splitlines()[start - 1 : node.end_lineno])
            parts.append(f"# {fname}:{node.lineno}\n{text}\n\n\n")
    OUT.write_text("".join(parts))
    print(f"wrote {OUT} ({sum(len(v) for v in WANT.values())} functions)")


if __name__ == "__main__":
    main()
