# SPDX-License-Identifier: Apache-2.0
"""GENERATED by FMS/tools/extract_legacy.py -- do not edit by hand.

Functions copied verbatim from FuzzingBrain's legacy strategies
(crs/strategy/jeff/xs0_delta.py and xs1_c_full.py, snapshot 4d7eee6c).
The names they need from the rest of the legacy script are provided below:
log_message writes to the FMS run log, call_llm goes to the FMS LLM client.
"""
import json
import os
import re
import textwrap
import time

_LLM = None      # set by FMS.substrate.bind_legacy()
_LOG = None


def log_message(log_file, message):
    if _LOG is not None:
        _LOG(message)


def call_llm(log_file, messages, model_name):
    return _LLM(messages, model_name)

# xs0_delta.py:2372
SYSTEM_PROMPT_DELTA = """
You are a world-leading top software vulnerability detection expert, which helps to find vulnerabilities. 
Do not aplogize when you are wrong. Just keep optimizing the result directly and proceed the progress. Do not lie or guess when you are unsure about the answer.
If possible, show the information needed to make the response better apart from the answer given. """

# xs1_c_full.py:2235
SYSTEM_PROMPT_FULL = """
You are a world-leading top software vulnerability detection expert, which helps to find vulnerabilities. 
Do not aplogize when you are wrong. Just keep optimizing the result directly and proceed the progress. Do not lie or guess when you are unsure about the answer.
If possible, show the information needed to make the response better apart from the answer given. """

# xs1_c_full.py:4429
MAX_INPUT_TOKENS = 100_000

# xs0_delta.py:165
def truncate_output(output, max_lines=200):
    """
    Truncate output to show only the first and last parts if it's too long.
    
    Args:
        output: The output string to truncate
        max_lines: Maximum number of lines to show
        
    Returns:
        str: Truncated output
    """
    lines = output.split('\n')
    if len(lines) <= max_lines:
        return output
    
    # Show first 100 and last 100 lines
    first_part = lines[:max_lines//2]
    last_part = lines[-(max_lines//2):]
    
    return '\n'.join(first_part) + '\n\n[...truncated...]\n\n' + '\n'.join(last_part)


# xs0_delta.py:1390
def filter_instrumented_lines(text, max_line_length=200):
    if not text:
        return text
    
    filtered_lines = []
    for line in text.splitlines():
        # Skip lines containing "INFO: Instrumented"
        if line.startswith("INFO: ") or "Server VM warning:" in line:
            continue
        # Drop noisy sanitizer/SQLite warnings
        if line.lstrip().startswith("WARNING:"):
            continue                        
        # Truncate long lines
        if len(line) > max_line_length:
            truncated = line[:max_line_length] + f" ... (truncated, full length: {len(line)})"
            filtered_lines.append(truncated)
        else:
            filtered_lines.append(line)
            
    return '\n'.join(filtered_lines)


# xs0_delta.py:2093
def extract_crash_output(output):
    """
    Extract the relevant crash output from fuzzer output.
    Handles various sanitizer errors, libFuzzer crashes, and Java exceptions.
    Returns up to MAX_SIZE bytes of the most relevant part of the crash.
    """
    # Maximum size to return (4KB)
    MAX_SIZE = 4096
    
    # Define patterns to look for, in order of priority
    patterns = [
        # AddressSanitizer errors
        {"marker": "ERROR: AddressSanitizer", "backtrack": False},
        # UndefinedBehaviorSanitizer errors
        {"marker": "ERROR: UndefinedBehaviorSanitizer", "backtrack": False},
        # MemorySanitizer errors
        {"marker": "ERROR: MemorySanitizer", "backtrack": False},
        {"marker": "WARNING: MemorySanitizer", "backtrack": False},
        # ThreadSanitizer errors
        {"marker": "ERROR: ThreadSanitizer", "backtrack": False},
        # LeakSanitizer errors
        {"marker": "ERROR: LeakSanitizer", "backtrack": False},
        # libFuzzer crash indicator
        {"marker": "==ERROR: libFuzzer", "backtrack": False},
        # SEGV indicator (with backtracking to find the start of the report)
        {"marker": "SUMMARY: AddressSanitizer: SEGV", "backtrack": True},
        # Generic sanitizer summary (with backtracking)
        {"marker": "SUMMARY: ", "backtrack": True},
        # Java exceptions - Jazzer format
        {"marker": "Uncaught exception:", "backtrack": False},
        # Alternative Java exception format
        {"marker": "Java Exception:", "backtrack": False},
        # Generic Java exception format
        {"marker": "Exception in thread", "backtrack": False}
    ]
    
    # Try each pattern
    for pattern in patterns:
        marker_index = output.find(pattern["marker"])
        if marker_index != -1:
            # Found a match
            start_idx = marker_index
            
            # If backtracking is enabled, try to find the start of the error report
            if pattern["backtrack"]:
                # Look for the nearest "==" before the marker
                error_start = output[:marker_index].rfind("==")
                if error_start != -1:
                    start_idx = error_start
                else:
                    error_start = output[:marker_index].rfind("runtime error:")
                    if error_start != -1:
                        start_idx = error_start
                                    
            # Extract up to MAX_SIZE bytes
            if len(output) - start_idx > MAX_SIZE:
                return output[start_idx:start_idx + MAX_SIZE]
            else:
                return output[start_idx:]
    
    # If no specific error marker found, return the last 4KB of output
    if len(output) > MAX_SIZE:
        return output[-MAX_SIZE:]
    
    return output


# xs0_delta.py:617
def process_large_diff(diff_content, log_file):
    """Process a large diff to extract the most relevant parts for vulnerability analysis"""
    # Split the diff into individual file changes
    file_diffs = re.split(r'diff --git ', diff_content)
    
    # The first element is usually empty or contains the commit message
    if file_diffs and not file_diffs[0].strip().startswith('a/'):
        header = file_diffs[0]
        file_diffs = file_diffs[1:]
    else:
        header = ""
    
    # Add the 'diff --git' prefix back to each file diff except the header
    file_diffs = ["diff --git " + d if d.strip() else d for d in file_diffs]
    
    # Extract useful information about the diff
    total_files = len(file_diffs)
    log_message(log_file, f"Diff contains changes to {total_files} files")
    
    # Focus only on C and Java files
    c_extensions = ['.c', '.h']
    java_extensions = ['.java']
    binary_indicators = ['Binary files', 'GIT binary patch']
    
    # Categorize files by language
    c_files = []
    java_files = []
    other_files = 0
    binary_files = 0
    
    for file_diff in file_diffs:
        if not file_diff.strip():
            continue
            
        # Skip binary files
        if any(indicator in file_diff for indicator in binary_indicators):
            binary_files += 1
            continue
        
        # Try to extract the filename
        match = re.search(r'a/([^\s]+)', file_diff)
        if not match:
            other_files += 1
            continue
            
        filename = match.group(1)
        ext = os.path.splitext(filename)[1].lower()
        
        # Categorize based on extension
        if ext in c_extensions:
            c_files.append((filename, file_diff))
        elif ext in java_extensions:
            java_files.append((filename, file_diff))
        else:
            other_files += 1
    
    log_message(log_file, f"Categorized files: {len(c_files)} C files, {len(java_files)} Java files, "
                          f"{binary_files} binary files, {other_files} other files")
    
    # Security keywords specific to C and Java
    c_security_keywords = [
        'overflow', 'underflow', 'bounds', 'check', 'validate', 'sanitize', 'input',
        'malloc', 'free', 'alloc', 'realloc', 'memcpy', 'strcpy', 'strncpy', 'strlcpy',
        'buffer', 'size', 'length', 'null', 'nullptr', 'crash', 'assert',
        'error', 'vulnerability', 'exploit', 'security', 'unsafe', 'safe',
        'race', 'deadlock', 'lock', 'mutex', 'semaphore', 'atomic',
        'format', 'printf', 'sprintf', 'fprintf', 'snprintf', 'scanf', 'sscanf',
        'exec', 'system', 'popen', 'shell', 'command', 'injection',
        'crypt', 'encrypt', 'decrypt', 'hash', 'sign', 'verify',
        'random', 'prng', 'secret', 'key', 'token', 'permission',
        'privilege', 'sandbox', 'container', 'isolation',
        'sizeof', 'pointer', 'array', 'index', 'out-of-bounds',
        'integer', 'signed', 'unsigned', 'cast', 'conversion',
        'stack', 'heap', 'use-after-free', 'double-free'
    ]
    
    java_security_keywords = [
        'overflow', 'underflow', 'bounds', 'check', 'validate', 'sanitize', 'input',
        'buffer', 'size', 'length', 'null', 'crash', 'assert', 'exception',
        'error', 'vulnerability', 'exploit', 'security', 'unsafe', 'safe',
        'race', 'deadlock', 'lock', 'mutex', 'semaphore', 'atomic', 'concurrent',
        'format', 'printf', 'String.format', 'injection', 'sql', 'query',
        'auth', 'password', 'crypt', 'encrypt', 'decrypt', 'hash', 'sign', 'verify',
        'certificate', 'random', 'SecureRandom', 'secret', 'key', 'token', 'permission',
        'privilege', 'sandbox', 'isolation', 'escape',
        'ClassLoader', 'Reflection', 'serialization', 'deserialization',
        'XSS', 'CSRF', 'SSRF', 'XXE', 'RCE', 'JNDI', 'LDAP', 'JMX',
        'ArrayIndexOutOfBoundsException', 'NullPointerException'
    ]
    
    # Score C files
    scored_c_files = []
    for filename, file_diff in c_files:
        score = 0
        
        # Check for security keywords in the diff
        for keyword in c_security_keywords:
            score += file_diff.lower().count(keyword) * 2
        
        # Check for added/removed lines that might indicate security changes
        added_lines = len(re.findall(r'^\+(?!\+\+)', file_diff, re.MULTILINE))
        removed_lines = len(re.findall(r'^-(?!--)', file_diff, re.MULTILINE))
        score += (added_lines + removed_lines) // 5  # More changes = higher score
        
        # Bonus for certain high-risk C functions or patterns
        high_risk_c_patterns = [
            'memcpy', 'strcpy', 'strcat', 'sprintf', 'gets', 'malloc', 'free', 
            'sizeof', '[', ']', '->', 'char *', 'void *', 'int *'
        ]
        for pattern in high_risk_c_patterns:
            score += file_diff.count(pattern) * 3
        
        scored_c_files.append((score, filename, file_diff))
    
    # Score Java files
    scored_java_files = []
    for filename, file_diff in java_files:
        score = 0
        
        # Check for security keywords in the diff
        for keyword in java_security_keywords:
            score += file_diff.lower().count(keyword) * 2
        
        # Check for added/removed lines that might indicate security changes
        added_lines = len(re.findall(r'^\+(?!\+\+)', file_diff, re.MULTILINE))
        removed_lines = len(re.findall(r'^-(?!--)', file_diff, re.MULTILINE))
        score += (added_lines + removed_lines) // 5  # More changes = higher score
        
        # Bonus for certain high-risk Java patterns
        high_risk_java_patterns = [
            'Runtime.exec', 'ProcessBuilder', 'System.load', 'URLClassLoader',
            'ObjectInputStream', 'readObject', 'Class.forName', 'reflection',
            'setAccessible', 'doPrivileged', 'native', 'JNI', 'array', 'index',
            'Exception', 'try', 'catch', 'finally', 'throw'
        ]
        for pattern in high_risk_java_patterns:
            score += file_diff.count(pattern) * 3
        
        scored_java_files.append((score, filename, file_diff))
    
    # Sort by score (highest first)
    scored_c_files.sort(reverse=True)
    scored_java_files.sort(reverse=True)
    
    # Build the processed diff
    processed_diff = header + "\n\n"
    processed_diff += f"# Processed diff summary: {total_files} files changed\n"
    
    # Determine which language to prioritize based on file counts and scores
    c_max_score = scored_c_files[0][0] if scored_c_files else 0
    java_max_score = scored_java_files[0][0] if scored_java_files else 0
    
    if len(c_files) > 0 and (len(java_files) == 0 or c_max_score >= java_max_score):
        # Prioritize C files
        processed_diff += f"# Showing most security-relevant changes from C files ({len(c_files)} total C files)\n\n"
        
        # Add the top N most relevant C files
        max_c_files = min(10, len(scored_c_files))
        for i, (score, filename, file_diff) in enumerate(scored_c_files[:max_c_files]):
            processed_diff += f"# C File {i+1}: {filename} (relevance score: {score})\n"
            processed_diff += file_diff + "\n\n"
        
        # Add some Java files if available and space permits
        if java_files and len(processed_diff) < 40000:
            max_java_files = min(3, len(scored_java_files))
            processed_diff += f"\n# Selected Java files ({max_java_files} of {len(java_files)})\n\n"
            for i, (score, filename, file_diff) in enumerate(scored_java_files[:max_java_files]):
                processed_diff += f"# Java File {i+1}: {filename} (relevance score: {score})\n"
                processed_diff += file_diff + "\n\n"
    else:
        # Prioritize Java files
        processed_diff += f"# Showing most security-relevant changes from Java files ({len(java_files)} total Java files)\n\n"
        
        # Add the top N most relevant Java files
        max_java_files = min(10, len(scored_java_files))
        for i, (score, filename, file_diff) in enumerate(scored_java_files[:max_java_files]):
            processed_diff += f"# Java File {i+1}: {filename} (relevance score: {score})\n"
            processed_diff += file_diff + "\n\n"
        
        # Add some C files if available and space permits
        if c_files and len(processed_diff) < 40000:
            max_c_files = min(3, len(scored_c_files))
            processed_diff += f"\n# Selected C files ({max_c_files} of {len(c_files)})\n\n"
            for i, (score, filename, file_diff) in enumerate(scored_c_files[:max_c_files]):
                processed_diff += f"# C File {i+1}: {filename} (relevance score: {score})\n"
                processed_diff += file_diff + "\n\n"
    
    log_message(log_file, f"Processed diff size: {len(processed_diff)} bytes (original: {len(diff_content)} bytes)")
    return processed_diff


# xs0_delta.py:2692
def create_commit_based_prompt(fuzzer_code, commit_diff, sanitizer, language):
    """
    Create a prompt for the LLM based on the fuzzer code, commit diff, language, and sanitizer.
    Handles C/C++ and Java projects differently and targets specific sanitizers.
    """
    # Base prompt that applies to all languages
    base_prompt = f"""
The provided commit introduces a vulnerability. Your job is to find the correct input to trigger the vulnerability.
Please output a Python script that creates a x.bin file. Your blob file will be run by this fuzzer code:
{fuzzer_code}

# Commit Diff
{commit_diff}
"""

    # C/C++ specific prompt with sanitizer targeting
    if language.startswith('c'):
        # Define sanitizer-specific guidance
        sanitizer_guidance = {
            "address": """
The target project uses AddressSanitizer, which detects:
- Buffer overflows (stack, heap, global)
- Use-after-free errors
- Use-after-return bugs
- Use-after-scope bugs
- Double-free errors

Your goal is to trigger an AddressSanitizer error by crafting an input that exploits the vulnerability.
""",
            "memory": """
The target project uses MemorySanitizer, which detects:
- Uninitialized memory reads
- Use of uninitialized values in conditional operations
- Passing uninitialized values to library functions

Your goal is to trigger a MemorySanitizer error by crafting an input that causes the program to use uninitialized memory.
""",
            "undefined": """
The target project uses UndefinedBehaviorSanitizer, which detects:
- Integer overflow/underflow
- Signed integer overflow
- Division by zero
- Null pointer dereference
- Misaligned pointer dereference
- Unreachable code
- Invalid enum values
- Floating-point errors

Your goal is to trigger an UndefinedBehaviorSanitizer error by crafting an input that causes undefined behavior.
"""
        }
        
        # Get the guidance for the specified sanitizer, or use a generic one if not found
        sanitizer_specific = sanitizer_guidance.get(sanitizer.lower(), """
The target project uses sanitizers that can detect various types of errors. Your goal is to trigger a sanitizer error by crafting an input that exploits the vulnerability.
""")
        
        language_specific = f"""
IMPORTANT: Read the harness code carefully to understand how inputs are processed. You need to generate a complete blob that will trigger a sanitizer error.

Think through these steps:
1. What function contains the vulnerability? How do you reach this function?
2. What input will trigger the vulnerability?
3. Are there any other inputs required before reaching the target function?
4. How does the harness code process inputs? Follow the instructions in the harness.
5. Combine all this information to generate a complete blob.
{sanitizer_specific}
"""

    # Java specific prompt
    else:
        language_specific = """
IMPORTANT: Read the harness code carefully to understand how inputs are processed. You need to generate a complete blob that will trigger a Jazzer sanitizer error or Java exception.

Think through these steps:
1. What method contains the vulnerability? How do you reach this method?
2. What input will trigger the vulnerability?
3. Are there any other inputs required before reaching the target method?
4. How does the harness code process inputs? Follow the instructions in the harness.
5. Combine all this information to generate a complete blob.

The target project uses Jazzer sanitizers that can detect various types of vulnerabilities:
- ClojureLangHooks: detects vulnerabilities in Clojure code
- Deserialization: detects unsafe deserialization
- ExpressionLanguageInjection: detects expression language injection
- FilePathTraversal: detects path traversal vulnerabilities
- LdapInjection: detects LDAP injection
- NamingContextLookup: detects JNDI injection
- OsCommandInjection: detects OS command injection
- ReflectiveCall: detects unsafe reflection
- RegexInjection: detects regex injection
- RegexRoadblocks: detects regex denial of service
- ScriptEngineInjection: detects script engine injection
- ServerSideRequestForgery: detects SSRF vulnerabilities
- SqlInjection: detects SQL injection
- XPathInjection: detects XPath injection

Your goal is to trigger any of these sanitizer errors or a Java exception (like NullPointerException, ArrayIndexOutOfBoundsException, etc.) by crafting an input that exploits the vulnerability.
"""

    # Common ending for both languages
    ending = """
Limit the blob size to 2MiB max

Your output must be a Python script that creates a file named exactly "x.bin" with a short description of the vulnerability and the target function.
"""

    # Combine the parts to create the final prompt
    return base_prompt + language_specific + ending


# xs1_c_full.py:4431
def _count_tokens(text: str) -> int:    # <- new helper
    """
    Best-effort Anthropic token counter.
    Uses anthropic.count_tokens if present; otherwise
    falls back to a 4-chars ≈ 1 token heuristic.
    """
    try:
        import anthropic
        return anthropic.Anthropic().count_tokens(text)
    except Exception:
        return max(1, len(text) // 4)   # rough upper bound


# xs1_c_full.py:4444
def find_most_likely_vulnerable_functions(log_file,reachable_funcs,language,model_name,
                                          top_k=10,
                                          timeout_sec=300):
    """
    reachable_funcs - list[dict]  each dict has `name` and `body`
    language        : "c" or "java"
    returns list[dict]  (name, score, reason)  or [] on failure
    """
    if not reachable_funcs:
        return []

    overhead_tokens = 2_000        # reserve budget for the rubric + system msg
    current_tokens  = overhead_tokens

    # 1. Build a concise catalogue of reachable functions
    func_catalog = []
    for f in reachable_funcs:
        name = f.get("name") or f.get("Name") or "<unknown>"
        body = (f.get("body") or f.get("Body") or
                f.get("sourceCode") or f.get("SourceCode") or "")
        snippet = f"Function: {name}\n{body}"
        func_catalog.append(snippet)

    catalog_text = "\n".join(func_catalog)

    # Count words
    word_count = len(re.findall(r'\w+', catalog_text))
    if word_count > 50_000:
        # Rebuild catalog, skipping functions with more than 500 lines
        func_catalog = []
        for f in reachable_funcs:
            name = f.get("name") or f.get("Name") or "<unknown>"
            body = (f.get("body") or f.get("Body") or
                    f.get("sourceCode") or f.get("SourceCode") or "")
            # Only include if <= 5000 lines
            if body.count('\n') <= 500:
                snippet = f"Function: {name}\n{body}"
                
                snippet_tokens = _count_tokens(snippet)
                if current_tokens + snippet_tokens > MAX_INPUT_TOKENS:
                    break                    # budget exhausted – stop adding functions

                func_catalog.append(snippet)
                current_tokens += snippet_tokens

        catalog_text = "\n".join(func_catalog)

    # 2. Construct the prompt
    prompt = textwrap.dedent(f"""
You are a world-class software security vulnerability researcher specialising in {language}.

Task
-----
Inspect **every** function reachable from the fuzzer entry-point and decide
whether it *likely* contains an off-by-one error, integer overflow, or buffer
over-read/write.  

Scoring rubric
---------------
10 — Certain off-by-one, integer-overflow **or** buffer-boundary violation (e.g. `memcpy(buf, src, len+1)`, `size * 2654435761u` wrapping, loop writes when `i == size`).  
7-9 — Very strong indicators (suspicious `<=` bounds, signed/unsigned length mismatch, multiplication that can wrap, calculated size exceeds buffer).  
4-6 — Possible boundary or integer-overflow issue; hints but not conclusive.  
1-3 — No evidence of off-by-one, integer-overflow, or buffer-boundary problems.

Return **JSON only**, no markdown, in this exact schema:

[
    {{"name":"<funcName>", "score":<1-10>, "reason":"<short>"}},
    ...
]

Provide at most {top_k} entries, sorted by descending score.
If **no** function merits a score ≥ 4, return an empty array: `[ ]`.  

Reachable functions:
{catalog_text}
""")

    # 3. Query the model
    messages = [
        {"role": "system", "content": "You are an expert in code security."},
        {"role": "user",   "content": prompt}
    ]
    start = time.time()
    raw, ok = call_llm(log_file, messages, model_name)
    duration = time.time() - start
    if not ok:
        log_message(log_file, f"[WARN] {model_name} failed in {duration:.1f}s\n")
        return []
 
    # Strip markdown fences if present
    m = re.search(r"```(?:json)?\s*([\s\S]*?)```", raw)
    if m:
        raw = m.group(1).strip()

    try:
        parsed = json.loads(raw)
        # basic sanity-check
        if isinstance(parsed, list) and parsed:
            log_message(log_file, f"top_k: {top_k} [parsed] {parsed}\n")
            return parsed[:top_k]
    except json.JSONDecodeError:
        log_message(log_file, f"[WARN] JSON parse failed for {model_name}: {raw}\n")

    return []


# xs1_c_full.py:4564
def extract_vulnerable_functions(reachable_funcs, vulnerable_functions, limit=10):
    """
    reachable_funcs      - list[dict]  each with Name/body/…
    vulnerable_functions - list[dict]  each with "name" (plus score, reason…)
    Returns a filtered list (≤ limit) containing only the vulnerable funcs.
    
    Args:
        reachable_funcs (list): List of dictionaries containing reachable functions
        vulnerable_functions (list): List of dictionaries containing vulnerable functions with scores and reasons
        limit (int): Maximum number of functions to return
        
    Returns:
        list: Filtered list of reachable functions with added score and reason from vulnerable_functions
    """
    if not vulnerable_functions:
        # nothing to filter by → return at most `limit` reachables
        return reachable_funcs[:limit]

    # Create a mapping of name to (score, reason) from vulnerable functions
    vuln_info = {}
    for vf in vulnerable_functions[:limit]:
        name = (vf.get("name") or vf.get("Name") or "").strip()
        if name:
            vuln_info[name] = {
                'score': vf.get('score', 0),
                'reason': vf.get('reason', '')
            }

    # Take the top `limit` vulnerable names
    wanted = set(vuln_info.keys())

    filtered = []
    for f in reachable_funcs:
        name = (f.get("name") or f.get("Name") or "").strip()
        if name in wanted:
            # Copy the function dict to avoid modifying the original
            func_with_info = f.copy()
            # Add score and reason from the corresponding vulnerable function
            func_with_info["score"] = vuln_info[name]['score']
            func_with_info["reason"] = vuln_info[name]['reason']
            filtered.append(func_with_info)

    return filtered


# xs1_c_full.py:4818
def get_vulnerable_function_entry(vulnerable_functions, vul_name):
    """
    Find and return the vulnerable function entry that matches the given name.
    
    Args:
        vulnerable_functions (list): List of dictionaries containing vulnerable function entries
        vul_name (str): Name of the vulnerable function to find
        
    Returns:
        dict: Matching vulnerable function entry or None if not found
    """
    for vf in vulnerable_functions:
        # Check both 'name' and 'Name' keys, consistent with the usage in the main code
        current_name = (vf.get('name') or vf.get('Name') or '').strip()
        if current_name == vul_name:
            return vf
    return None


# xs1_c_full.py:4836
def _iter_chunks(seq, chunk_size: int):
    """Yield successive *chunk_size*-long slices from *seq*."""
    for i in range(0, len(seq), chunk_size):
        yield seq[i : i + chunk_size]


# xs1_c_full.py:4896
def covert_target_functions_format(reachable_funcs):
    """
    Convert reachable_funcs (list of FunctionDefinition) into simplified_modified_functions format:
    {
        file_path1: [{"name": func_name1, "start_line": line1}, ...],
        file_path2: [{"name": func_name2, "start_line": line2}, ...],
        ...
    }
    """
    simplified_modified_functions = {}

    for func in reachable_funcs:
        file_path = func.get("FilePath") or func.get("file_path")
        name = func.get("Name") or func.get("name")
        start_line = func.get("StartLine") or func.get("start_line")

        if not file_path or not name or start_line is None:
            continue  # Skip incomplete entries

        if file_path not in simplified_modified_functions:
            simplified_modified_functions[file_path] = []

        simplified_modified_functions[file_path].append({
            "name": name,
            "start_line": start_line
        })

    return simplified_modified_functions


# xs1_c_full.py:4841
def create_call_path_info_prompt(main_call_path,language):
    """
    Create a prompt focused on call path.
    Args:
        main_call_path: a list of function info dictionaries
    """
    call_path_info = "# Vulnerability Call Path\n\n"
    call_path_info += "The following call path leads to the vulnerability:\n\n"
     
    # Create a visual representation of the call path
    call_path_diagram = "## Call Sequence\n\n"
    call_path_diagram += "```\n"
    
    for i, node_data in enumerate(main_call_path):
        function_name = node_data.get('function', 'unknown')
        file_name = os.path.basename(node_data.get('file', 'unknown'))
        is_modified = node_data.get('is_modified', False)

        prefix = "→ " if i > 0 else ""
        highlight = "**" if is_modified else ""
        
        call_path_diagram += f"{prefix}{highlight}{function_name}(){highlight} ({file_name})\n"
        
        if i < len(main_call_path) - 1:
            call_path_diagram += "    |\n    ↓\n"
    
    call_path_diagram += "```\n\n"
    call_path_info += call_path_diagram
    
    # Add detailed information about each function in the call path
    call_path_info += "## Function Details\n\n"
    for i, node_data in enumerate(main_call_path):
        file_path = node_data.get('file', 'unknown')
        function_name = node_data.get('function', 'unknown')
        function_body = node_data.get('body', '')
        is_modified = node_data.get('is_modified', False)
        
        # Add information about whether this function was modified
        modification_status = " (**MODIFIED in commit**)" if is_modified else ""
        
        call_path_info += f"{i+1}. {function_name}(){modification_status}\n"
        call_path_info += f"- **File**: {file_path}\n"
        if function_name == "fuzzerTestOneInput" or function_name == "LLVMFuzzerTestOneInput":
            call_path_info +="\n"
            continue
        
        # # Only show code for non-empty function bodies
        # if function_body.strip():
        #     call_path_info += f"- **Code**:\n```{language.lower()}\n{function_body.strip()}\n```\n\n"
        # else:
        #     call_path_info += f"- **Code**: (not available)\n\n"
  
    return call_path_info


# xs1_c_full.py:4176
def create_full_scan_prompt(
        fuzzer_code: str,
        sanitizer: str,
        language: str,
        call_path_prompt: str,
        reachable_funcs: list[dict] | None = None,
        vulnerable_funcs: list[dict] | None = None,
        max_blob_mb: int = 2,
) -> str:
    """
    Build a rich prompt for FULL_SCAN mode.

    """

    # ──────────────────────────────────────────────────────────────────────
    base_prompt = f"""
You are an elite software-vulnerability researcher specialising in {language}.
The target binary is built with sanitizers; your goal is to craft **input(s)**
that crash the program (ASan/MSan/UBSan/Jazzer, etc.).  The harness that feeds
data into the target looks like:

```{language}
{fuzzer_code}
```
(Study how the input is read!)

"""
    entrypoint = "fuzzerTestOneInput"
    if language.startswith('c'):
        entrypoint = "LLVMFuzzerTestOneInput"

    if reachable_funcs:
        # reachable_funcs format: [{"Name": "...", "SourceCode": "..."} , …]
        func_snippets = []
        for f in reachable_funcs:
            name = f.get("name") or f.get("Name") or "<unknown>"
            body = (f.get("body") or f.get("Body") or
                    f.get("sourceCode") or f.get("SourceCode") or "")
            snippet = f"Function: {name}\n{body}"
            func_snippets.append(snippet)

        funcs_block = "\n\n".join(func_snippets) if func_snippets else "<call-graph unavailable>"

        base_prompt += f"""
We have pre-analysed the call-graph.  The entry point is `{entrypoint}`.
The following reachable functions might be risky (full bodies included):

{funcs_block}
"""

    if vulnerable_funcs:
        vf_lines = []
        for vf in vulnerable_funcs:
            name   = vf.get("name") or vf.get("Name") or "<unknown>"
            score  = vf.get("score", "?")
            reason = vf.get("reason", "").strip()
            vf_lines.append(f"• {name} - {reason}")
        vf_block = "\n".join(vf_lines)

        base_prompt += f"""
Here are the reasons why these functions are risky, per static heuristics:

{vf_block}
"""

    # ── sanitizer guidance (C/C++) ───────────────────────────────────────
    if language.startswith('c'):
        san_guide = {
            "address": (
                "AddressSanitizer reports buffer overflows, use-after-free, "
                "double-free, etc.  Classic triggers:\n"
                "• Oversized length fields\n"
                "• Negative indices casted to large unsigned values\n"
                "• String without null-terminator\n"
            ),
            "memory": (
                "MemorySanitizer flags reads of uninitialised memory.  Classic "
                "triggers:\n"
                "• Partially initialised structs\n"
                "• Checksum fields that skip bytes\n"
            ),
            "undefined": (
                "UndefinedBehaviorSanitizer catches UB: integer overflow, "
                "division by zero, invalid shift, mis-aligned pointer, etc.\n"
                "Classic triggers: 0-byte allocations, INT_MAX+1 lengths, "
                "null deref, etc.\n"
            ),
        }.get(sanitizer.lower(), "")
        language_block = f"""
### Sanitizer Focus  ({sanitizer})
{san_guide}

### Plan
1. Map input bytes → parser structure (see harness).
2. Choose a vulnerable target function.
3. Devise an input to reach and corrupt it.
4. Comment the reasoning before writing code.

"""
    else:  # Java / Jazzer
        language_block = """
### Jazzer Focus
Try to trigger Jazzer crash with "Java Exception: com.code_intelligence.jazzer", e.g. deserialization-based RCE, backdoor, regex DoS, path traversal,
reflection misuse, SQL/LDAP/XPath injection, etc.
"""

    ending = f"""
### Deliverable
• Produce a **single Python 3 script** that writes **x.bin** (binary mode).
• If you have multiple candidate payloads, emit them all (x1.bin, x2.bin, ..., x5.bin, at most five).
• Max size per blob: **{max_blob_mb} MiB**.
• Put a short header comment explaining the vulnerability.

Write nothing except the Python script (with embedded comments)."""

    return base_prompt + call_path_prompt + language_block + ending


