"""
PoV Strategy
Base class for all POV (Proof of Vulnerability) generation strategies
"""
import os
import sys
import shutil
import json
import subprocess
import time
import uuid
import glob
import select
from abc import abstractmethod
from typing import Tuple, Dict, Any, List, Optional
from pathlib import Path

from core.base_strategy import BaseStrategy
from common.utils import (
    get_commit_info,
    extract_python_code_from_response,
    filter_instrumented_lines,
    extract_crash_output,
    extract_crash_trace,
    generate_vulnerability_signature,
    cleanup_seed_corpus,
    truncate_output,
)

# Constants
DETECT_TIMEOUT_CRASH_SENTINEL = "detect_timeout_crash"


class PoVStrategy(BaseStrategy):
    """
    Base class for POV generation strategies

    Subclasses MUST implement:
    - do_pov(initial_msg) -> Tuple[bool, dict]
    - submit_pov(metadata) -> bool

    Provides optional methods with default implementations:
    - execute_core_logic() - Main flow (find fuzzer, get commit, create prompt, call do_pov)
    - create_initial_prompt() - Creates basic commit-based prompt
    - generate_blobs() - Executes Python code to create 1 blob (x.bin)
    - generate_pov() - Calls LLM to generate POV code
    - run_fuzzer() - Runs fuzzer with blob files
    - find_fuzzer_source() - Finds fuzzer source code
    - save_pov_artifacts() - Saves successful POV files
    - has_successful_pov() - Checks for existing POVs
    - check_for_successful_patches() - Checks for successful patches

    All optional methods can be overridden for custom behavior.
    """

    # ========== Abstract methods (subclasses MUST implement) ==========

    @abstractmethod
    def do_pov(self, initial_msg: str) -> Tuple[bool, Dict[str, Any]]:
        """
        Main POV generation loop - MUST be implemented by subclasses

        Args:
            initial_msg: Initial prompt for the LLM

        Returns:
            Tuple of (success: bool, metadata: dict)
        """
        pass

    @abstractmethod
    def submit_pov(self, pov_metadata: Dict[str, Any]) -> bool:
        """
        Submit POV to endpoint - MUST be implemented by subclasses

        Args:
            pov_metadata: POV metadata to submit

        Returns:
            True if submission successful, False otherwise
        """
        pass

    # ========== Optional methods with default implementations ==========

    def execute_core_logic(self) -> bool:
        """
        Execute POV generation logic
        Called by BaseStrategy.run()

        Default implementation:
        - Find fuzzer source code
        - Get commit info
        - Create initial prompt
        - Call do_pov()

        Can be overridden for completely custom flow
        """
        self.logger.log("Starting POV generation...")

        # Find fuzzer source code
        fuzzer_code = self.find_fuzzer_source()
        if not fuzzer_code:
            self.logger.error("Failed to find fuzzer source code")
            return False

        # Get commit information
        commit_msg, commit_diff = get_commit_info(
            self.config.project_dir,
            self.config.language,
            logger=self.logger
        )

        # Create initial prompt (strategy-specific)
        initial_msg = self.create_initial_prompt(fuzzer_code, commit_diff)

        # Execute POV generation loop
        success, metadata = self.do_pov(initial_msg)

        return success

    def create_initial_prompt(self, fuzzer_code: str, commit_diff: str) -> str:
        """
        Create the initial prompt for POV generation

        Default implementation creates a basic commit-based prompt.
        Strategies can override for custom prompts (e.g., AS0 multi-phase)

        Args:
            fuzzer_code: Source code of the fuzzer
            commit_diff: Commit diff introducing the vulnerability

        Returns:
            Initial prompt string for LLM
        """
        prompt = f"""You are a security researcher analyzing a fuzzer and a vulnerability.

Fuzzer code:
```
{fuzzer_code}
```

Vulnerability commit diff:
```
{commit_diff}
```

Your task is to create a test input (blob file) that will trigger the vulnerability when fed to this fuzzer.
Please write a Python script that generates the blob file as 'x.bin'.
"""
        return prompt

    def generate_blobs(self, code: str, xbin_dir: str) -> List[str]:
        """
        Execute LLM-generated Python code to create blob files

        Default implementation:
        - Executes Python code in a subprocess
        - Returns ["/path/to/x.bin"] (1 blob)

        AS0 strategy overrides to generate 5 blobs (x1.bin - x5.bin)

        Args:
            code: Python code generated by LLM
            xbin_dir: Directory to store blob files

        Returns:
            List of blob file paths
        """
        # Save code to temp file
        code_file = os.path.join(xbin_dir, "generate_blob.py")
        with open(code_file, "w") as f:
            f.write(code)

        # Execute code
        try:
            result = subprocess.run(
                [sys.executable, code_file],
                cwd=xbin_dir,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                raise RuntimeError(f"Code execution failed: {result.stderr}")

            # Check for x.bin
            blob_path = os.path.join(xbin_dir, "x.bin")
            if not os.path.exists(blob_path):
                raise RuntimeError("Code did not create x.bin")

            return [blob_path]

        except subprocess.TimeoutExpired:
            raise RuntimeError("Code execution timed out")
        except Exception as e:
            raise RuntimeError(f"Code execution error: {str(e)}")

    # ========== Tool methods (can be overridden if needed) ==========

    def generate_pov(self, messages: List[Dict[str, str]], model_name: str) -> str:
        """
        Generate POV code using LLM

        Default implementation:
        - Call LLM with messages
        - Extract Python code from response

        Can be overridden if needed
        """
        # Log the user input (last user message in the conversation)
        user_messages = [m for m in messages if m.get("role") == "user"]
        if user_messages:
            last_user_msg = user_messages[-1].get("content", "")
            self.logger.log_user_input(last_user_msg, round_number=len(user_messages))

        start_time = time.time()
        response, success = self.llm_client.call(messages, model_name)
        end_time = time.time()

        self.logger.log_time(start_time, end_time, "generate_pov", f"Model: {model_name}")

        if not success:
            self.logger.warning(f"LLM call failed with model {model_name}")
            return ""

        # Log the LLM response
        self.logger.log_llm_response(response, model_name=model_name)

        # Extract Python code from response
        code = extract_python_code_from_response(
            response,
            self.llm_client,
            max_retries=2,
            timeout=30,
            logger=self.logger
        )

        if not code:
            self.logger.warning("Failed to extract Python code from LLM response")
            return ""

        self.logger.log(f"Successfully generated {len(code)} characters of POV code")
        return code

    def run_fuzzer(self, blob_paths: List[str]) -> Tuple[bool, str]:
        """
        Run fuzzer with generated blob(s)

        Default implementation runs fuzzer in Docker container with libFuzzer.
        Strategies can override for custom fuzzer execution.

        Args:
            blob_paths: List of blob file paths to test

        Returns:
            Tuple of (crash_detected: bool, fuzzer_output: str)
        """
        # Run fuzzer with the first blob
        # (For strategies with multiple blobs, they can override this)
        blob_path = blob_paths[0]

        if not os.path.exists(blob_path):
            self.logger.error(f"Blob file not found: {blob_path}")
            return False, ""

        is_c_project = self.config.language.startswith('c')

        try:
            self.logger.log(f"Running fuzzer {self.config.fuzzer_path} with blob {blob_path}")

            # Get fuzzer directory and name
            fuzzer_dir = os.path.dirname(self.config.fuzzer_path)
            fuzzer_name = os.path.basename(self.config.fuzzer_path)

            # For NGINX testing only (ignore if test_nginx is False)
            if self.config.test_nginx:
                run_pov_command = ["./run.sh", "run_pov", blob_path, "pov_harness"]
                result = subprocess.run(
                    run_pov_command,
                    cwd=self.config.project_dir,
                    capture_output=True,
                    text=True,
                    timeout=60
                )
            else:
                # Extract project name and sanitizer from fuzzer path
                # Example: /app/.../build/out/libpng-address/libpng_read_fuzzer
                path_parts = fuzzer_dir.split('/')

                # Find project-sanitizer part (e.g., "libpng-address")
                project_sanitizer = None
                for part in path_parts:
                    if '-' in part and any(san in part for san in ['address', 'undefined', 'memory']):
                        project_sanitizer = part
                        break

                if not project_sanitizer:
                    self.logger.error(f"Could not determine project and sanitizer from path: {self.config.fuzzer_path}")
                    return False, f"Could not determine project and sanitizer from path: {self.config.fuzzer_path}"

                # Split into project and sanitizer
                parts = project_sanitizer.split('-')
                sanitizer = parts[-1]  # Last part is sanitizer
                project_name = '-'.join(parts[:-1])  # Rest is project name

                sanitizer_project_dir = os.path.join(self.config.project_dir, f"{self.config.focus}-{sanitizer}")
                out_dir = os.path.dirname(self.config.fuzzer_path)
                out_dir_x = os.path.join(out_dir, "xp0")

                work_dir = os.path.join(
                    self.config.project_dir,
                    "fuzz-tooling", "build", "work",
                    f"{project_name}-{sanitizer}"
                )

                # Create unique blob name to avoid race conditions
                unique_id = str(uuid.uuid4())[:8]
                unique_blob_name = f"x_{unique_id}.bin"
                docker_blob_path = os.path.join(out_dir_x, unique_blob_name)

                # Copy blob to docker-accessible location
                try:
                    shutil.copy(blob_path, docker_blob_path)
                    self.logger.log(f"Copied blob to {docker_blob_path}")
                except Exception as e:
                    self.logger.error(f"Failed to copy blob: {str(e)}")
                    return False, f"Failed to copy blob: {str(e)}"

                # Find Docker image (try aixcc-afc first, then gcr.io/oss-fuzz)
                docker_image = None

                # Check aixcc-afc/{project_name}
                try:
                    result = subprocess.run(
                        ["docker", "images", f"aixcc-afc/{project_name}", "--format", "{{.Repository}}:{{.Tag}}"],
                        capture_output=True, text=True, timeout=60
                    )
                    if result.returncode == 0 and result.stdout.strip():
                        docker_image = result.stdout.strip().split('\n')[0]
                except Exception as e:
                    self.logger.warning(f"Failed to find docker image for aixcc-afc/{project_name}: {str(e)}")

                # If not found, check gcr.io/oss-fuzz/{project_name}
                if not docker_image:
                    try:
                        result = subprocess.run(
                            ["docker", "images", f"gcr.io/oss-fuzz/{project_name}", "--format", "{{.Repository}}:{{.Tag}}"],
                            capture_output=True, text=True, timeout=60
                        )
                        if result.returncode == 0 and result.stdout.strip():
                            docker_image = result.stdout.strip().split('\n')[0]
                    except Exception as e:
                        self.logger.warning(f"Failed to find docker image for gcr.io/oss-fuzz/{project_name}: {str(e)}")

                if not docker_image:
                    self.logger.error(f"Failed to find docker image for {project_name}")
                    return False, f"Failed to find docker image for {project_name}"

                self.logger.log(f"Found docker image: {docker_image}")

                # Build Docker command
                docker_cmd = [
                    "docker", "run", "--rm",
                    "--platform", "linux/amd64",
                    "-e", "FUZZING_ENGINE=libfuzzer",
                    "-e", f"SANITIZER={sanitizer}",
                    "-e", "ARCHITECTURE=x86_64",
                    "-e", f"PROJECT_NAME={project_name}",
                    "-v", f"{sanitizer_project_dir}:/src/{project_name}",
                    "-v", f"{out_dir_x}:/out",
                    "-v", f"{work_dir}:/work",
                    docker_image,
                    f"/out/{fuzzer_name}",
                    "-timeout=30",
                    "-timeout_exitcode=99",
                    f'/out/{unique_blob_name}'
                ]

                # Add coverage options for control flow analysis (if enabled)
                if hasattr(self.config, 'use_control_flow') and self.config.use_control_flow:
                    if not is_c_project:
                        # For Java projects (e.g., zookeeper)
                        if self.config.project_name == "zookeeper":
                            docker_cmd.insert(-3, f"--instrumentation_includes=org.apache.zookeeper.**")
                        docker_cmd.insert(-3, f"--coverage_dump=/out/coverage.exec")

                self.logger.log(f"Running Docker command: {' '.join(docker_cmd)}")

                result = subprocess.run(
                    docker_cmd,
                    capture_output=True,
                    text=True,
                    timeout=60
                )

            # Analyze result
            combined_output = result.stderr + "\n" + result.stdout

            # Quick path: successful execution without crash
            if result.returncode == 0 and "ABORTING" not in combined_output:
                self.logger.log("Fuzzer ran successfully without crashing")
                return False, combined_output

            # Java NoClassDefFoundError is not a crash
            if result.returncode == 77 and "Java Exception: java.lang.NoClassDefFoundError:" in combined_output:
                self.logger.log(f"Fuzzer exited with code {result.returncode}, but no crash indicators found")
                return False, combined_output

            # Check for assertion failures
            if "assertion failed" in combined_output.lower():
                self.logger.log("Fuzzer crashed with assertion failed")
                return True, combined_output

            # Log stderr if present
            if result.stderr:
                self.logger.log(f"Fuzzer stderr: {result.stderr}")

            # Define crash indicators
            crash_indicators = [
                "ERROR: AddressSanitizer:",
                "ERROR: MemorySanitizer:",
                "WARNING: MemorySanitizer:",
                "ERROR: ThreadSanitizer:",
                "ERROR: UndefinedBehaviorSanitizer:",
                "SEGV on unknown address",
                "Segmentation fault",
                "runtime error:",
                "AddressSanitizer: heap-buffer-overflow",
                "AddressSanitizer: heap-use-after-free",
                "UndefinedBehaviorSanitizer: undefined-behavior",
                "AddressSanitizer:DEADLYSIGNAL",
                "Java Exception: com.code_intelligence.jazzer",
                "ERROR: HWAddressSanitizer:",
                "WARNING: ThreadSanitizer:",
                "libfuzzer exit=1"
            ]

            # Check for timeout crash detection (if enabled)
            sentinel = Path(self.config.project_dir) / "detect_timeout_crash"
            if os.environ.get("DETECT_TIMEOUT_CRASH") == "1" or sentinel.exists():
                crash_indicators.append("ERROR: libFuzzer: timeout")
                crash_indicators.append("libfuzzer exit=99")

            # Check for crash
            if result.returncode != 0 or "ABORTING" in combined_output:
                if any(indicator in combined_output for indicator in crash_indicators):
                    self.logger.log(f"Fuzzer crashed with exit code {result.returncode} - vulnerability triggered!")
                    return True, combined_output
                else:
                    self.logger.log(f"Fuzzer exited with code {result.returncode}, but no crash indicators found")
                    return False, combined_output

            return False, combined_output

        except subprocess.TimeoutExpired:
            self.logger.warning("Fuzzer execution timed out")
            return False, "Execution timed out"
        except Exception as e:
            self.logger.error(f"Error running fuzzer: {str(e)}")
            return False, str(e)

    def find_fuzzer_source(self) -> str:
        """
        Find and return fuzzer source code

        Default implementation uses heuristics and optional LLM to find the source.
        Strategies can override for custom logic.

        Returns:
            Source code of the fuzzer as a string
        """
        from common.utils import find_fuzzer_source

        self.logger.log("Finding fuzzer source code...")

        # Determine project source directory
        project_src_dir = os.path.join(self.config.project_dir, self.config.focus)

        # Call utility function
        fuzzer_code = find_fuzzer_source(
            fuzzer_path=self.config.fuzzer_path,
            project_name=self.config.project_name,
            project_src_dir=project_src_dir,
            focus=self.config.focus,
            language=self.config.language,
            test_nginx=self.config.test_nginx,
            llm_client=self.llm_client,
            logger=self.logger
        )

        if fuzzer_code and "Could not find" not in fuzzer_code:
            self.logger.log(f"Successfully found fuzzer source ({len(fuzzer_code)} characters)")
        else:
            self.logger.warning("Could not find fuzzer source code")

        return fuzzer_code

    def save_pov_artifacts(
        self,
        pov_id: str,
        model_name: str,
        iteration: int,
        code: str,
        blob_path: str,
        fuzzer_output: str,
        messages: List[Dict[str, str]]
    ) -> Dict[str, Any]:
        """
        Save successful POV artifacts

        Saves:
        - Python code that generated the POV
        - Blob file
        - Fuzzer output
        - Conversation history
        - Metadata
        """
        save_dir = self.config.pov_success_dir

        try:
            os.makedirs(save_dir, exist_ok=True)
        except PermissionError:
            pov_base_dir = os.environ.get('POV_OUTPUT_DIR', '/tmp/povs')
            save_dir = os.path.join(pov_base_dir, os.path.basename(save_dir))
            os.makedirs(save_dir, exist_ok=True)
            self.logger.warning(f"Cannot write to {self.config.pov_success_dir}, using {save_dir}")

        # Save POV Python code
        pov_file_path = os.path.join(save_dir, f"pov_{pov_id}_{model_name}_{iteration}.py")
        with open(pov_file_path, "w") as f:
            f.write(code)
        self.logger.log(f"Saved POV code to {pov_file_path}")

        # Save blob file
        blob_file = f"test_blob_{pov_id}_{model_name}_{iteration}.bin"
        if os.path.exists(blob_path):
            shutil.copy(blob_path, os.path.join(save_dir, blob_file))

        # Save fuzzer output
        crash_output = extract_crash_output(fuzzer_output)
        fuzzer_output_file = f"fuzzer_output_{pov_id}_{model_name}_{iteration}.txt"
        with open(os.path.join(save_dir, fuzzer_output_file), "w") as f:
            f.write(crash_output)

        # Save conversation history
        conversation_file = f"conversation_{pov_id}_{model_name}_{iteration}.json"
        with open(os.path.join(save_dir, conversation_file), "w") as f:
            json.dump(messages, f, indent=2)

        # Create vulnerability signature
        vuln_signature = f"{self.config.fuzzer_name}-{generate_vulnerability_signature(crash_output, self.config.sanitizer)}"

        # Create POV metadata
        pov_metadata = {
            "conversation": conversation_file,
            "fuzzer_output": fuzzer_output_file,
            "blob_file": blob_file,
            "fuzzer_name": self.config.fuzzer_name,
            "sanitizer": self.config.sanitizer,
            "project_name": self.config.project_name,
            "pov_signature": vuln_signature,
        }

        # Save metadata
        metadata_file = f"pov_metadata_{pov_id}_{model_name}_{iteration}.json"
        metadata_path = os.path.join(save_dir, metadata_file)
        with open(metadata_path, "w") as f:
            json.dump(pov_metadata, f, indent=2)

        self.logger.log(f"Saved POV metadata to {metadata_path}")
        self.logger.log(f"POV SUCCESS! Vulnerability triggered with {model_name} on iteration {iteration}")

        return pov_metadata

    def check_for_successful_patches(self) -> bool:
        """Check if successful patches exist"""
        # TODO: Implement patch checking
        return False

    def has_successful_pov(self) -> bool:
        """Check if successful POV already exists"""
        if not os.path.exists(self.config.pov_success_dir):
            return False
        pov_files = [f for f in os.listdir(self.config.pov_success_dir) if f.startswith("pov_metadata_")]
        return len(pov_files) > 0
